apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fineract-platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: brac-fineract
  
  source:
    repoURL: https://github.com/0sifat/fineract.git
    targetRevision: HEAD
    path: kubernetes  # Remove the leading slash okk 
  
  destination:
    server: https://kubernetes.default.svc
    namespace: fineract
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m