apiVersion: v1
kind: Service
metadata:
  labels:
    app: fineract-server
  name: fineract-server
spec:
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: fineract-server
    tier: backend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract-server
  namespace: fineract
  labels:
    app: fineract-server
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fineract-server
      tier: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fineract-server
        tier: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - |
              echo "Testing connection to fineractmysql:3306"
              until nc -z fineractmysql 3306; do
                echo "Waiting for MySQL server..."
                sleep 5
              done
              echo "MySQL server is ready!"
              sleep 10
      containers:
        - name: fineract-server
          image: apache/fineract:latest
          env:
            - name: FINERACT_SERVER_PORT
              value: "8443"
            - name: FINERACT_SERVER_SSL_ENABLED
              value: "true"
            - name: FINERACT_HIKARI_JDBC_URL
              value: "jdbc:mariadb://fineractmysql:3306/fineract_tenants?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: FINERACT_HIKARI_USERNAME
              value: "root"
            - name: FINERACT_HIKARI_PASSWORD
              value: "mysql"
            - name: FINERACT_HIKARI_DRIVER_CLASS_NAME
              value: org.mariadb.jdbc.Driver
            - name: FINERACT_DEFAULT_TENANTDB_HOSTNAME
              value: "fineractmysql"
            - name: FINERACT_DEFAULT_TENANTDB_PORT
              value: "3306"
            - name: FINERACT_DEFAULT_TENANTDB_UID
              value: "root"
            - name: FINERACT_DEFAULT_TENANTDB_PWD
              value: "mysql"
            - name: FINERACT_DEFAULT_TENANTDB_CONN_PARAMS
              value: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx1G -Xms512m -Djava.security.egd=file:/dev/./urandom"
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /fineract-provider/actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /fineract-provider/actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: 8443