apiVersion: v1
kind: Secret
metadata:
  name: fineract-tenants-db-secret
  namespace: fineract
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  # echo -n "root" | base64
  username: cm9vdA==
  # echo -n "mysql" | base64
  password: bXlzcWw=