apiVersion: v1
kind: Service
metadata:
  labels:
    app: mifos-community
  name: mifos-community
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 80
  selector:
    app: mifos-community
    tier: frontend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mifos-community
  labels:
    app: mifos-community
spec:
  selector:
    matchLabels:
      app: mifos-community
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mifos-community
        tier: frontend
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', 'echo "Checking for Fineract server"; until nc -z fineract-server 8443; do sleep 5; echo "Waiting..."; done; echo "Fineract server ready!";']  # Fixed: simple service name
      containers:
      - name: mifos-community
        image: openmf/community-app:latest
        env:
          - name: BASE_API_URL
            value: "https://fineract-server:8443/fineract-provider"  # Fixed: simple service name
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "0.5Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        ports:
        - containerPort: 80