apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineractmysql
  labels:
    app: fineract-mysql
spec:
  selector:
    matchLabels:
      app: fineract-mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fineract-mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: mariadb:11.4
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "mysql"
          ports:
            - containerPort: 3306
          # ✅ FIXED PROBES (use tcpSocket instead of exec)
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: fineractmysql-initdb
              mountPath: /docker-entrypoint-initdb.d/
            - name: fineractmysql-persistent-storage
              mountPath: /var/lib/mysql/
      volumes:
        - name: fineractmysql-initdb
          configMap:
            name: fineractmysql-initdb
        - name: fineractmysql-persistent-storage
          persistentVolumeClaim:
            claimName: fineractmysql-pv-claim
