apiVersion: v1
kind: Secret
metadata:
  name: fineract-tenants-db-secret
  namespace: fineract
type: Opaque
data:
  # Generate with: echo -n "username" | base64
  username: dXNlcm5hbWU=
  # Generate with: echo -n "password" | base64  
  password: cGFzc3dvcmQ=
