apiVersion: v1
kind: Service
metadata:
  labels:
    app: fineract-server
  name: fineract-server
spec:
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: fineract-server
    tier: backend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract-server
  namespace: fineract
  labels:
    app: fineract-server
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1  # Start with 1 for debugging
  selector:
    matchLabels:
      app: fineract-server
      tier: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fineract-server
        tier: backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.28
          command:
            - 'sh'
            - '-c'
            - |
              echo "Testing connection to fineractmysql:3306"
              until nc -z fineractmysql 3306; do  # Fixed: simple service name
                echo "Waiting for MySQL server..."
                sleep 5
              done
              echo "MySQL server is ready!"
              sleep 10
      containers:
        - name: fineract-server
          image: apache/fineract:latest
          env:
            - name: FINERACT_HIKARI_JDBC_URL
              value: "jdbc:mariadb://fineractmysql:3306/fineract_tenants?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"  # Fixed: simple service name
            - name: FINERACT_HIKARI_USERNAME
              value: "root"  # Direct value for testing
            - name: FINERACT_HIKARI_PASSWORD
              value: "mysql"  # Direct value for testing
            - name: FINERACT_HIKARI_DRIVER_CLASS_NAME
              value: org.mariadb.jdbc.Driver
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx1G -Xms512m -Djava.security.egd=file:/dev/./urandom"
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /fineract-provider/actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /fineract-provider/actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 120
            periodSeconds: 20
          ports:
            - containerPort: 8443